### ISSUE TITLE
TipViewStyle

### ISSUE THREAD

**Issue by Natelegreat1** [jordibruin/TipKit-Examples#8]
I was trying to figure out a way to customize the TipView styling using `TipViewStyle` but it seems as though using it hides the default dismiss ("x") button.

I've asked the question in [Developer Forums](https://developer.apple.com/forums/thread/736561) but considering you're one of the few (other) people who have put some time into playing with TipKit, maybe you have some insight?

<img src=https://developer.apple.com/forums/content/attachment/bf80f484-4fc3-4a33-b353-baa9cbbbdea3>

I was hoping there would be a way to use `TipView` and have an arrow... but alas...

Thanks for any insight you may have! :)

**Comment by jordibruin** [comment]
Have not had a look in a while, I'll investigate!

**Comment by jordibruin** [comment]
@melsam do you happen to know if this is intended?

**Comment by melsam** [comment]
When you use a custom tip view style, it is treated as a "blank canvas" and you're free to insert any views into it that you like including a custom close button. The link in the Developer Forums above includes some code that you can use to insert a close button into the custom tip view.
